name: Continuous Integration
on: 
  push:
    branches: [main]

jobs:
  build:
    name: Build and Test for Integration
    runs-on: Ubuntu-latest

    # Environment variables for test database
    env:
      DB_USER : root
      DB_PASSWORD: root
      DB_DATABASE: test_db
      DB_HOST: localhost
  
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install Dependencies
      run: |
        pip install pytest pytest-cov
        pip install flask
        pip install mysql-connector-python
        pip install python-dotenv
        
    - name: Checkout Development Code
      uses: actions/checkout@v4
      with: 
        repository: DevOps2023TeamD/TeamD_Assignment

    - name: Checkout Private Repo
      uses: actions/checkout@v4
      with:
        repository: DevOps2023TeamD/TeamD_Assignment_QA
        token: ${{ secrets.TEAMD_QA }}
        path: hiddenCode

    - name: List Current Files
      run: |
        ls
        sudo mv ./hiddenCode/*.* ./

    # Set up testing database 
    - name: Set up MySQL
      run: |
        sudo /etc/init.d/mysql start
        mysql -h localhost --port 3306 -u$DB_USER -p$DB_PASSWORD -e "DROP DATABASE IF EXISTS test_db;"
        mysql -h localhost --port 3306 -u$DB_USER -p$DB_PASSWORD < create_test_db.sql
        mysql -h localhost --port 3306 -u$DB_USER -p$DB_PASSWORD -e "USE test_db; SHOW TABLES;"

    - name: Test Pytest
      if: always()
      run: |
        pytest -v -cov --junitxml=report.xml
        
    - if: ${{ failure() }}
      name: Create Issue on Failed workflow
      uses: dacbd/create-issue-action@main
      with: 
        token: ${{ github.token }}
        title: Action workflow Workflow name - `${{ github.workflow }}` failed.
        body: |
          ### Context
          [Failed Run](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
          [Codebase](https://github.com/${{ github.repository }}/tree/${{ github.sha }})
          Workflow name - `${{ github.workflow }}`
          Job -           `${{ github.job }}`
          status -        `${{ job.status }}`
          assignees: YaSwe

    - if: ${{ failure() }}
      name: Discord notification on Failed workflow
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      uses: Ilshidur/action-discord@master
      with:
        args: 'One of the test cases in {{ EVENT_PAYLOAD.repository.full_name }} has failed.'
          
    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action/composite@v2
      if: always()
      with: 
        junit_files: "report.xml"

    - name: Prepare Results
      run: |
        mkdir downloads
        mv report.xml ./downloads
    - name: Upload Test Results
      uses: actions/upload-artifact@v2
      with: 
        name: testResults
        path: downloads
        
    - name: Download Remote Test Results
      uses: actions/download-artifact@v2
      with:
        name: testResults

  lint:
  name: Lint Code Base
  runs-on: ubuntu-latest
  steps:
  - uses: actions/checkout@v4
  - name: Super Linter
    uses: super-linter/super-linter@v5.7.2
    env: 
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      DEFAULT_BRANCH: main
      VALIDATE_ALL_CODEBASE: false
      VALIDATE_PYTHON_BLACK: false
      VALIDATE_GITHUB_ACTIONS: false
      PYTHON_FLAKE8_CONFIG_FILE: .flake8
